import type { RagArchitecture } from '../../types'

/**
 * ADOP — the AWS sample for agent-generated data pipelines.
 *
 * NAMING: AWS's own materials disagree. The Machine Learning blog announcing it
 * calls it the "Agentic Data Operations Platform"; the GitHub Pages docs site
 * uses "Agentic Data Onboarding Platform" in places, and the central component
 * is unambiguously the "Data Onboarding Agent". The repo is
 * aws-samples/sample-Agentic-Ai-Data-Operations. We lead with Operations
 * (blog + repo agree) and flag the discrepancy rather than pick silently.
 */

const ONBOARD_PROMPT = `# The entire pipeline is specified in one prompt.
/onboard-workflow HIPAA

Onboard claims data from
  s3://data-lake-<account>-us-east-1/bronze/claims/ingestion_date=YYYY-MM-DD/claims.csv
into Silver with dedup on claim_id and a not-null policy_number rule,
and into a flat denormalized Gold Iceberg table with derived measures
(net_paid_ratio, days_to_submission, denial_category).

Run daily at 03:00 UTC. Apply HIPAA controls with PHI masking in Silver.
`

const SUBAGENT_PY = `# Sub-agents are ZERO-TOOL by design: they generate files and nothing else.
# They cannot call MCP servers or AWS APIs — Cedar policy denies it, so a
# prompt injection in the source data cannot escalate into an AWS action.
#
# Structured output via Bedrock tool_choice, parsed straight into dataclasses:
# no brittle regex over free text.

response = bedrock.converse(
    modelId=MODEL_ID,
    messages=[{"role": "user", "content": [{"text": profile_prompt}]}],
    toolConfig={
        "tools": [{"toolSpec": {
            "name": "emit_semantic_model",
            "inputSchema": {"json": SEMANTIC_YAML_SCHEMA},
        }}],
        # Force the model to answer *as* the tool call — the output is typed.
        "toolChoice": {"tool": {"name": "emit_semantic_model"}},
    },
)

block = next(b for b in response["output"]["message"]["content"] if "toolUse" in b)
semantic = SemanticModel(**block["toolUse"]["input"])   # typed, not parsed prose
`

const QUALITY_DQDL = `# Generated by the Quality Agent as AWS Glue Data Quality (DQDL) rules.
# Critical rules BLOCK promotion to the next zone; the DAG fails the task.

Rules = [
    # --- Silver: earned the right to be trusted ---
    IsComplete   "claim_id",                          # 100% — it is the dedup key
    IsUnique     "claim_id",                          # must hold *after* dedup
    Completeness "policy_number" >= 0.95,
    ColumnValues "claim_received_date" <= now(),

    # --- Gold: analytics-grade or it does not ship ---
    Completeness "net_paid_ratio" >= 0.99,
    ColumnValues "net_paid_ratio" between 0 and 1.5,  # catches billing anomalies
]
`

const DAG_PY = `# Generated by the DAG Agent. Every zone hop is followed by its quality gate,
# so bad data stops at the boundary instead of reaching analysts.
from airflow import DAG
from airflow.providers.amazon.aws.operators.glue import GlueJobOperator

with DAG(
    "claims_data",
    schedule="0 3 * * *",              # daily 03:00 UTC, as asked for in the prompt
    catchup=False,
    default_args={"retries": 3, "retry_exponential_backoff": True},
) as dag:
    bronze = GlueJobOperator(task_id="extract_bronze", job_name="load_bronze_claims")
    gate_b = GlueJobOperator(task_id="quality_gate_bronze", job_name="dq_bronze")
    silver = GlueJobOperator(task_id="transform_to_silver", job_name="bronze_to_silver")
    gate_s = GlueJobOperator(task_id="quality_gate_silver", job_name="dq_silver")
    gold   = GlueJobOperator(task_id="transform_to_gold", job_name="silver_to_gold")
    gate_g = GlueJobOperator(task_id="quality_gate_gold", job_name="dq_gold")
    catalog = GlueJobOperator(task_id="register_catalog", job_name="lf_register")

    bronze >> gate_b >> silver >> gate_s >> gold >> gate_g >> catalog
`

export const agenticDataOps: RagArchitecture = {
  id: 'agentic_data_ops',
  name: 'Agentic Data Operations (ADOP)',
  tagline: 'One prompt in, a governed Bronze→Silver→Gold pipeline out.',
  difficulty: 'production',
  family: 'agentic-data-engineering',

  summary:
    'Standing up a data pipeline normally means a Spark engineer, a dbt developer, an orchestration specialist and a compliance reviewer working in sequence over weeks. ADOP collapses that into a single natural-language request: describe the source, the rules and the schedule, and an orchestrating agent generates the transformation code, the quality rules, the Airflow DAG and the governance tags — then deploys them. The engineer reviews and approves rather than writes.',
  technicalSummary:
    'A Data Onboarding Agent runs a five-phase pipeline (health check → discovery/dedup → profiling → parallel build → deploy). Phase 4 spawns four sub-agents — Metadata, Transformation, Quality and DAG — which return structured JSON via Bedrock tool_choice, parsed into typed dataclasses. Those sub-agents are deliberately zero-tool: they emit files and cannot invoke MCP servers or AWS APIs, a boundary enforced by Cedar policy rather than by prompt instruction. Generated artifacts land as Glue PySpark jobs writing Iceberg tables across medallion zones, Glue Data Quality (DQDL) rulesets gating each hop, an Airflow DAG on MWAA, and Lake Formation LF-Tags applying column-level TBAC to detected PII. Agents run in development only; artifacts promote to higher environments through CI/CD.',

  whenToUse: [
    'Repeatedly onboarding new datasets into a medallion lake where the shape of the work is the same and only the schema differs.',
    'Regulated data (HIPAA, GDPR, PCI, SOX) where masking, retention and column-level access must be provably applied every time.',
    'Small teams that need pipeline throughput without hiring a specialist for each layer of the stack.',
  ],
  whenNotToUse: [
    'A single stable pipeline that already exists and rarely changes — the generation machinery is overhead you never amortise.',
    'Streaming or sub-minute latency requirements; this pattern targets scheduled batch onto Iceberg tables.',
    'Teams unwilling to review generated code — the model is engineer-approves-output, not engineer-out-of-the-loop.',
    'Environments where you cannot run agents in a development account and promote artifacts through CI/CD.',
  ],
  enterpriseConsiderations: [
    'Trust boundary: sub-agents hold no tools, so a prompt injection hidden in source data has no AWS API to reach. That boundary lives in Cedar policy, not in a system prompt that can be argued with.',
    'Auditability: artifacts are deterministic — checksums, fixed timestamps, seeded randomness — so the same inputs regenerate byte-identical output, and CloudTrail records every grant and table creation.',
    'Cost: agent generation is a one-off per dataset; the recurring bill is ordinary Glue, MWAA and Athena usage. The saving is engineer-weeks, not compute.',
    'Review burden shifts rather than disappears: someone must still read the generated PySpark and quality thresholds before they run against production data.',
    'PII detection is model-driven and therefore fallible. Treat the discovery block as a proposal requiring human confirmation, not a finding.',
    'This is an AWS sample, not a managed service. Read it as a reference architecture to adapt — verify every API against current docs before building on it.',
  ],

  layers: [
    { id: 'src_csv', label: 'Source CSV in S3', layer: 'sources', role: 'corpus', awsServiceId: 's3', note: 'daily partition' },
    { id: 'router', label: 'Router agent (REIC)', layer: 'orchestration', role: 'router', awsServiceId: 'bedrock_foundation_models', note: 'TF-IDF dedup vs existing workloads' },
    { id: 'orchestrator', label: 'Data Onboarding Agent', layer: 'orchestration', role: 'supervisor', awsServiceId: 'bedrock_foundation_models', note: '5-phase run; holds all tools' },
    { id: 'subagents', label: 'Metadata · Transform · Quality · DAG', layer: 'ingestion', role: 'generator', awsServiceId: 'bedrock_foundation_models', note: 'zero-tool, parallel' },
    { id: 'mcp_tools', label: 'MCP tool servers', layer: 'ingestion', role: 'tools', awsServiceId: 'mcp', note: '13 servers, tiered REQUIRED/WARN/OPTIONAL' },
    { id: 'bronze_tbl', label: 'Bronze (raw, immutable)', layer: 'bronze', role: 'landing-zone', awsServiceId: 's3_tables', note: 'Iceberg; no transformation' },
    { id: 'glue_bronze', label: 'Glue ingest job', layer: 'bronze', role: 'etl', awsServiceId: 'glue' },
    { id: 'silver_tbl', label: 'Silver (deduped, masked)', layer: 'silver', role: 'conformed-zone', awsServiceId: 's3_tables', note: 'PHI masked; zone-scoped CMK' },
    { id: 'dq_silver', label: 'Quality gate (DQDL)', layer: 'silver', role: 'quality-gate', awsServiceId: 'glue_data_quality', note: 'critical rules block promotion' },
    { id: 'gold_tbl', label: 'Gold (derived measures)', layer: 'gold', role: 'serving-zone', awsServiceId: 's3_tables', note: 'flat wide Iceberg table' },
    { id: 'dq_gold', label: 'Quality gate (score ≥ 0.95)', layer: 'gold', role: 'quality-gate', awsServiceId: 'glue_data_quality' },
    { id: 'catalog', label: 'Glue Data Catalog', layer: 'gold', role: 'catalog', awsServiceId: 'glue_data_catalog' },
    { id: 'athena_q', label: 'Athena / BI', layer: 'consumption', role: 'query', awsServiceId: 'athena' },
    { id: 'airflow', label: 'Airflow DAG on MWAA', layer: 'orchestration', role: 'scheduler', awsServiceId: 'mwaa', note: 'daily 03:00 UTC, 3 retries' },
    { id: 'lf_tags', label: 'Lake Formation LF-Tags', layer: 'guardrails', role: 'policy', awsServiceId: 'lake_formation', note: 'column-level TBAC on PII' },
    { id: 'cedar', label: 'Cedar policies', layer: 'guardrails', role: 'policy', awsServiceId: 'verified_permissions', note: '23 policies; sub-agents get no tools' },
    { id: 'kms_keys', label: 'Zone-scoped KMS keys', layer: 'guardrails', role: 'encryption', awsServiceId: 'kms' },
    { id: 'audit', label: 'CloudTrail audit', layer: 'observability', role: 'audit', awsServiceId: 'cloudtrail' },
  ],

  walkthrough: [
    {
      id: 'phase0_intake',
      order: 1,
      title: 'State the pipeline in one prompt',
      plainExplanation:
        'Instead of filing tickets across four teams, an engineer describes the dataset in plain English: where it lives, how to dedupe it, what the schedule is, and which regulation applies. Everything downstream is generated from that.',
      technicalDetail:
        'The request names the regulation up front (HIPAA here), which selects a self-contained regulation prompt — controls apply only when the regulation is chosen. A Router Agent first runs RAG-Enhanced Intent Classification (TF-IDF similarity over existing workload metadata) to check the dataset is not already onboarded, then a health check classifies 13 MCP servers as REQUIRED, WARN or OPTIONAL. If a REQUIRED server is down the run blocks rather than degrading silently.',
      diagramComponentIds: ['src_csv', 'router', 'orchestrator', 'mcp_tools'],
      codeSampleId: 'onboard_prompt',
      awsServiceIds: ['s3', 'bedrock_foundation_models', 'mcp'],
      costNotes: ['Health check and discovery are cheap; the expensive phase is profiling, which samples ~5% of the source.'],
    },
    {
      id: 'phase3_profile',
      order: 2,
      title: 'Profile the data and find the PII',
      plainExplanation:
        'The system samples the file, works out what each column is for — amounts, dates, categories — and flags the ones that look like personal data. It then shows that back for confirmation before anything is built.',
      technicalDetail:
        'The Metadata Agent samples ~5% of the CSV, infers schema and column roles (measures, dimensions, temporal), and runs model-driven PII detection across 12 types. In the claims example it flags member_ssn and member_email as CRITICAL and member_dob as HIGH. Detection is a proposal: the discovery block is presented for human confirmation, and the answers are written to workload memory so a later re-onboarding starts with context instead of re-asking.',
      diagramComponentIds: ['src_csv', 'subagents', 'orchestrator'],
      awsServiceIds: ['bedrock_foundation_models', 's3'],
    },
    {
      id: 'phase4_build',
      order: 3,
      title: 'Four sub-agents build in parallel — with no tools',
      plainExplanation:
        'Four specialists work at once: one writes the data model, one the transformation code, one the quality rules, one the schedule. Crucially none of them can touch AWS — they only write files, which the orchestrator later applies.',
      technicalDetail:
        'Metadata, Transformation, Quality and DAG agents run concurrently, each returning structured JSON via Bedrock tool_choice parsed into typed dataclasses — no regex over prose. All four are zero-tool: file generation only, no MCP and no AWS API, enforced by Cedar policy. That is the load-bearing security property here, because the agents are reasoning over untrusted source data. Each writes its own tests, and every test must pass before Phase 5 begins (max two retries per gate).',
      diagramComponentIds: ['subagents', 'cedar', 'orchestrator'],
      codeSampleId: 'subagent_py',
      codeHighlightRange: [[8, 22]],
      awsServiceIds: ['bedrock_foundation_models', 'verified_permissions'],
    },
    {
      id: 'zones',
      order: 4,
      title: 'Move Bronze → Silver → Gold, gated at each hop',
      plainExplanation:
        'Raw data lands untouched. The next zone deduplicates it, masks the personal fields and rejects rows missing a policy number. The final zone adds the calculated business measures. Each step has to pass its quality check before the next one runs.',
      technicalDetail:
        'Generated PySpark runs as Glue jobs writing Iceberg tables. Bronze is immutable and unencrypted-at-zone-level; Silver deduplicates on claim_id (keeping latest by claim_received_date), drops null policy_number, casts dates and masks PHI under a HIPAA-tier CMK; Gold flattens to a wide analytical table with net_paid_ratio, days_to_submission and denial_category. Glue Data Quality rulesets gate each promotion — critical rules such as uniqueness of the dedup key, or net_paid_ratio outside [0, 1.5], fail the task rather than passing bad data forward.',
      diagramComponentIds: ['glue_bronze', 'bronze_tbl', 'silver_tbl', 'dq_silver', 'gold_tbl', 'dq_gold', 'kms_keys'],
      codeSampleId: 'quality_dqdl',
      awsServiceIds: ['glue', 's3_tables', 'glue_data_quality', 'kms'],
      costNotes: ['Recurring cost is ordinary Glue DPU-hours plus Iceberg storage; the agent run itself is a one-off per dataset.'],
    },
    {
      id: 'schedule',
      order: 5,
      title: 'Schedule it on MWAA with gates as tasks',
      plainExplanation:
        'The generated schedule runs the whole chain every morning, retries transient failures, and alerts a mailbox if a quality check fails.',
      technicalDetail:
        'The DAG Agent emits an Airflow DAG with the quality gates as first-class tasks between each transformation, three retries with exponential backoff, and SNS alerting on failure. Before deploy, Phase 4.5 validates it: Python syntax compiles, Airflow can import the DAG without exceptions, imports resolve, and eight Airflow best-practice patterns are enforced — with inline auto-fix capped at two attempts before human escalation.',
      diagramComponentIds: ['airflow', 'dq_silver', 'dq_gold'],
      codeSampleId: 'dag_py',
      // The whole DAG body: the schedule and retry config through the
      // transformation -> gate -> transformation dependency chain.
      codeHighlightRange: [[6, 20]],
      awsServiceIds: ['mwaa', 'glue'],
    },
    {
      id: 'govern',
      order: 6,
      title: 'Register, tag and prove it',
      plainExplanation:
        'The tables are registered so analysts can query them, the personal columns are locked to a privileged role only, and every permission change is recorded for the auditor.',
      technicalDetail:
        'Phase 5 registers the three tables in the Glue Data Catalog, applies LF-Tags (PII_Classification=CRITICAL/HIGH) to the detected columns, and grants column-level TBAC — analysts_role on non-PHI, hipaa_admin_role on PHI. Seven post-deployment checks then run as verification rather than assumption: Athena actually returns rows, LF-Tags are present on the masked columns, the analyst role is genuinely denied PHI, the CMK exists with rotation enabled, the DAG imports cleanly in MWAA, CloudTrail shows the events, and Bronze versioning blocks deletes.',
      diagramComponentIds: ['catalog', 'lf_tags', 'athena_q', 'audit'],
      awsServiceIds: ['glue_data_catalog', 'lake_formation', 'athena', 'cloudtrail'],
    },
  ],

  codeSamples: [
    {
      id: 'onboard_prompt',
      title: 'The whole pipeline, as one request',
      language: 'bash',
      filename: 'onboard-workflow.txt',
      code: ONBOARD_PROMPT,
      explanation:
        'Naming the regulation selects a self-contained control prompt, so HIPAA masking and retention apply only when asked for. Everything else — dedup key, null policy, derived measures, schedule — is stated once and becomes generated code.',
    },
    {
      id: 'subagent_py',
      title: 'Structured output from a zero-tool sub-agent',
      language: 'python',
      filename: 'metadata_agent.py',
      code: SUBAGENT_PY,
      explanation:
        'Two ideas worth stealing regardless of ADOP. Forcing toolChoice makes the model answer as a typed schema rather than prose you then regex. And giving the sub-agent no tools at all means untrusted source data cannot reach an AWS API through it — a boundary in policy, not in a system prompt.',
    },
    {
      id: 'quality_dqdl',
      title: 'Generated Glue Data Quality rules',
      // DQDL is its own language; python highlighting renders its # comments
      // and list syntax correctly, and the app only ships four grammars.
      language: 'python',
      filename: 'quality_rules.dqdl',
      code: QUALITY_DQDL,
      explanation:
        'DQDL is AWS Glue Data Quality’s open rule language. Marking rules critical is what turns a dashboard metric into a gate: the DAG task fails and the next zone never runs.',
    },
    {
      id: 'dag_py',
      title: 'Generated Airflow DAG with gates between zones',
      language: 'python',
      filename: 'claims_data_dag.py',
      code: DAG_PY,
      explanation:
        'The shape that matters is transformation → gate → transformation → gate. Bad data stops at a zone boundary instead of arriving in Gold and being discovered by an analyst.',
    },
  ],

  awsServiceIds: [
    'bedrock_foundation_models',
    'glue',
    'glue_data_quality',
    'glue_data_catalog',
    's3_tables',
    'mwaa',
    'lake_formation',
    'athena',
    's3',
    'kms',
    'cloudtrail',
    'verified_permissions',
    'mcp',
  ],

  references: [
    { label: 'ADOP — architecture documentation (aws-samples)', url: 'https://aws-samples.github.io/sample-Agentic-Ai-Data-Operations/', kind: 'github' },
    { label: 'Agentic Data Operations Platform (ADOP) — AWS ML Blog', url: 'https://aws.amazon.com/blogs/machine-learning/agentic-data-operations-platform-adop-data-engineering-into-hours/', kind: 'aws-blog' },
    { label: 'AWS Glue Data Quality — DQDL reference', url: 'https://docs.aws.amazon.com/glue/latest/dg/glue-data-quality.html', kind: 'aws-docs' },
    { label: 'Amazon MWAA — user guide', url: 'https://docs.aws.amazon.com/mwaa/latest/userguide/what-is-mwaa.html', kind: 'aws-docs' },
    { label: 'AWS Lake Formation — tag-based access control', url: 'https://docs.aws.amazon.com/lake-formation/latest/dg/what-is-lake-formation.html', kind: 'aws-docs' },
    { label: 'Amazon S3 Tables (Apache Iceberg)', url: 'https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-tables.html', kind: 'aws-docs' },
    { label: 'Amazon Verified Permissions (Cedar)', url: 'https://docs.aws.amazon.com/verifiedpermissions/latest/userguide/what-is-avp.html', kind: 'aws-docs' },
  ],

  accentColor: '#0EA5E9',
}
